### ISSUE TITLE
Graphql 16 update

### ISSUE THREAD

**Issue by romainPrignon** [dimatill/graphql-middleware#500]
I couldn't wait anymore, so I fork the project: https://github.com/GeorgesTech/graphql-middleware
Changes: https://github.com/GeorgesTech/graphql-middleware/pull/1
And I used it like this: 
```json
{
  "graphql-middleware": "github:GeorgesTech/graphql-middleware#chore/graphql-16",
}
```

I do not plan to maintain the fork
I hope the issue will resolve soon

In the meantime, renovate/dependabot is happy

**Comment by jebenois** [comment]
Any updates on that one?

**Comment by icazemier** [comment]
+1

**Comment by alaarihan-temco** [comment]
+1

**Comment by romainPrignon** [comment]
I moved to https://www.graphql-yoga.com/ V2 from https://www.the-guild.dev/
I just had to replace some middlewares with https://www.envelop.dev/ plugins also from the-guild

If you happened to use the fork: https://github.com/GeorgesTech/graphql-middleware
I'll keep the fork public for 1 month
I'll delete it at the beginning of Jully

Happy migration :)

**Comment by eroist** [comment]
dose graphql-middleware support graphql@v16?

**Comment by curbol** [comment]
Is that alternative to graphql-middleware? this is a bit silly how longs it's taking to update to graphql 16

**Comment by simon-abbott** [comment]
@curbol We just successfully replaced `graphql-middleware` with `@graphql-tools/resolvers-composition`.

**Comment by farawaysouthwest** [comment]
I cut a PR for this, we'll see what happens.

**Comment by dimatill** [comment]
https://github.com/dimatill/graphql-middleware/pull/556 now graphql-middleware supports graphql v16 🎉
