### ISSUE TITLE
Could not find a declaration file for module 'graphql-middleware'. 

### ISSUE THREAD

**Issue by Golomidov-Danil** [dimatill/graphql-middleware#558]
![Code_LTAUS8TFff](https://user-images.githubusercontent.com/42399845/201180081-cae6e2bf-6c1c-437c-b638-84570a7ee639.png)
I use import instead of require(), maybe that's the problem?

**Comment by tsteenkamp** [comment]
You could try updating eslint & eslint typescript package versions. I guess for me that fixed the error.
